apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rag-demo.fullname" . }}-config
  labels:
    {{- include "rag-demo.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: {{ .Values.config.datasourceUrl | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.config.datasourceUsername | quote }}
  SPRING_AI_MODEL_CHAT: {{ .Values.config.llmProvider | quote }}
