apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rag-demo.fullname" . }}-secret
  labels:
    {{- include "rag-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.datasourcePassword | quote }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicApiKey | quote }}
